### ISSUE TITLE
Add built in Recycle Bin

### ISSUE THREAD

**Issue by itsmeshibintmz** [jerichoi224/Nothing-Gallery#38]
Even though the app supports deleting photos/videos, the fact that there is no recycle bin is not good as it should be a priority one.

Also deleting photos/videos is kinda buggy, shows white screen after deleting.(Nb:file is getting deleted)

**Comment by jerichoi224** [comment]
Thanks for the feedback. 
Recycle bin was also a feature I wanted to add before releasing, but I couldn't figure out how to add it..
Seems like Android just adds .trashed_ prefix to the file, and keeps it for a while, but I gotta figure out how I can get these files using flutter framework. 

This will be one of the higher priority once I figure out how to do it..

**Comment by jerichoi224** [comment]
Regarding the bug, could you describe more on how it happens?
I only got my Nohting PHone 1 to test, and I don't get those issues, making it hard to fix.

There are many ways/screens you can delete photos/vidoes like deleting from a single image view, deleting from the album grid view after selection, or deleting from the timeline view. does the white screen happen in all cases? or in specific cases?

**Comment by itsmeshibintmz** [comment]
> Seems like Android just adds .trashed_ prefix to the file and keeps it for a while so it is visible from other apps that have recycle bins, but I gotta figure out how I can get these files using flutter framework.

yeah I'm also trying in between, if anything pops up, 'll commit. Thanks for the quick response. :)

**Comment by itsmeshibintmz** [comment]
> There are many ways/screens you can delete photos/vidoes like deleting from a single image view, deleting from the album grid view after selection, or deleting from the timeline view. does the white screen happen in all cases? or in specific cases?

I've deleted from the image view. haven't tried any other scenarios. Using NP1.

**Comment by itsmeshibintmz** [comment]
> Regarding the bug, could you describe more on how it happens?

After I delete the file, the screen will look like this, app is not crashing or anything, just shows this white screen.

![Screenshot_20231013-234219](https://github.com/jerichoi224/Nothing-Gallery/assets/52344717/c948c3a7-e3d1-4546-a281-a8e8e15a0528)

**Comment by jerichoi224** [comment]
Ughh yeah, worst part about mobile dev is that same devices show different results :(

I haven't seen an issue with deleting on my nothing phone, but I have seen issues with my z flip, so there does seem to be an issue with deleting. It's gonna be hard to fix your issue because I can't debug it directly ,but I'll see if I can fix it.

Could you provide a bit more info?
- where did you enter the image from? The album or timeline?
- if album, was It the only photo? Or first/last photo?
- does it happen all the time?
- does deleting from grid view after deleting work fine?
Thx!

**Comment by nityamkaushik** [comment]
Hello can u send me ur application i really need it

**Comment by itsmeshibintmz** [comment]
> Hello can u send me ur application i really need it

https://github.com/jerichoi224/Nothing-Gallery/releases/tag/v0.5.2

**Comment by itsmeshibintmz** [comment]
Closing this as no comments were updated from the owner for the past 1 year.
