### ISSUE TITLE
Not showing any information 

### ISSUE THREAD

**Issue by itsmeshibintmz** [jerichoi224/Nothing-Gallery#39]
![Screenshot_20231013-234325.png](https://github.com/jerichoi224/Nothing-Gallery/assets/52344717/12c46bd4-0859-4073-97ac-4237ccc73544)

Even though there is a more options button for more details/tools, it doesn't do anything. It shows clicking, but nothing pops up. I would love to have information about the picture/video.

**Comment by itsmeshibintmz** [comment]
![Screenshot_20231013-234325.png](https://github.com/jerichoi224/Nothing-Gallery/assets/52344717/86529184-f98a-4f61-9227-c7c8e39e3d70)

Attached screenshot for reference.

**Comment by jerichoi224** [comment]
Ahh you're right. The app is still in development, and there are some buttons that don't do anything,
mainly the button you mentioned, and the info button from the video player. Will probably implement sth soon, but will take some time. 
Thanks for the feedback!

**Comment by itsmeshibintmz** [comment]
> Will probably implement sth soon, but will take some time.

Yes thank you :) . Really loved the design and implementation. Thank you.

**Comment by itsmeshibintmz** [comment]
Closing this as no comments were updated from the owner for the past 1 year.
